sequenceDiagram 

actor Bruker 

participant App

participant API

Bruker --> App: Click on retrieve weather button.

App -->> API: fetchWeatherData()

alt success

    API ---> App: Weather Data is returned

    App ---> Bruker: Show weather data

else fail

    API ---> APP: Error
    App ---> Bruker: Show error message

end